git:
  paging:
    colorArg: always
    pager: diff-so-fancy
    # https://github.com/jesseduffield/lazygit/issues/893
    # pager: delta --24-bit-color=never
  pull:
    mode: 'rebase'

gui:
  skipstashwarning: true
  skipunstagelinewarning: false
  theme:
    lighttheme: true
    ActiveBorderColor:
      - bold
    InactiveBorderColor:
      - black

startuppopupversion: 1
quitOnTopLevelReturn: true
