git:
  disableForcePushing: true
  paging:
    colorArg: always
    pager: delta --24-bit-color=never --paging=never
  pull:
    mode: 'rebase'

gui:
  sidePanelWidth: 0.25
  skipstashwarning: true
  skipunstagelinewarning: false
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - black

startuppopupversion: 1
quitOnTopLevelReturn: true
keybinding:
    files:
      commitChanges: 'C'
      commitChangesWithEditor: 'c'
    commits:
      renameCommit: 'R'
      renameCommitWithEditor: 'r'
